# Generated by Django 5.2.17 on 2026-08-22 18:23

import betat_community.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityConfig',
            fields=[
                ('id', models.CharField(max_length=253, primary_key=True, serialize=False, validators=[betat_community.core.models.validate_fqdn])),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('scientific_observation', 'Scientific observation'), ('creative_work', 'Creative work'), ('oral_knowledge', 'Oral knowledge'), ('personal_testimony', 'Personal testimony'), ('indigenous_knowledge', 'Indigenous knowledge'), ('religious_text', 'Religious text'), ('legal_record', 'Legal record'), ('historical_record', 'Historical record'), ('other', 'Other')], max_length=32)),
                ('hi_standard', models.TextField(default='human-originated, community-verified')),
                ('auth_methods', models.JSONField(validators=[betat_community.core.models.validate_auth_methods])),
                ('store_uri', models.CharField(max_length=500)),
            ],
        ),
    ]
