# Generated by Django 5.2.17 on 2026-08-23 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityconfig',
            name='peer_vouch_threshold',
            field=models.IntegerField(default=2, help_text='Minimum vouchers PeerVouchAuth requires. Default 2 (BLUEPRINT §3 Decision Log); communities may raise it, never lower it.', validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='communityconfig',
            name='trusted_institutions',
            field=models.JSONField(blank=True, default=dict, help_text="InstitutionalAuth's trust table: {institution_id: public_key_hex}."),
        ),
    ]
