"""
Django settings for betat_community project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = os.environ.get('BETAT_DEBUG', 'true').lower() in ('1', 'true', 'yes')

SECRET_KEY = os.environ.get('BETAT_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Dev-only fallback — never used when DEBUG is False, so it can be
        # committed safely. Production installs must set BETAT_SECRET_KEY.
        SECRET_KEY = 'django-insecure-3bx3ny^00-=-0lpac%@chtl_1u%w8fv(y=0w7$ap8vc&2nc_&2'
    else:
        raise ImproperlyConfigured(
            'BETAT_SECRET_KEY must be set in the environment when BETAT_DEBUG is false.'
        )

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # third-party
    'rest_framework',
    'rest_framework.authtoken',
    # betat apps
    'betat_community.core',
    'betat_community.store',
    'betat_community.communityauth',
    'betat_community.workflow',
    'betat_community.federation',
    'betat_community.bundledui',
] 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'betat_community.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'betat_community.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#SQLite_DB
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('BETAT_DB') or str(BASE_DIR / 'betat.sqlite3'),
    }
}

#POSTGRES_DB
# DATABASES = {
#     'default' : {
#         'ENGINE': 'django.db.backends.postgresql',
#         'OPTIONS' : {'options': '-c search_path=betchema'},
#         'NAME' :  'betatdb',
#         'USER' :  'betuser',
#         'PASSWORD' : 'panda#1',
#         'HOST' : 'localhost',
#         'PORT' : '5432',
#     }
# }

#TEST_DB
# DATABASES = {
#     'default' : {
#         'ENGINE': 'django.db.backends.postgresql',
#         # 'OPTIONS' : {'options': '-c search_path=betchema'},
#         'NAME' :  'betat_testdb',
#         'USER' :  'betester',
#         'PASSWORD' : 'alltest#1',
#         'HOST' : 'localhost',
#         'PORT' : '5432',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
# Reading endpoints are always public (BLUEPRINT §0); writing endpoints
# require a Provenancier/verifier token — issued via rest_framework.authtoken
# at successful communityauth enrollment (§03). "No custom crypto" for token
# issuance (todos/03-authentication.md) — this is DRF's standard mechanism.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

# Discoverability (§09) — see core/announce.py. No default: the registry's
# own announce contract isn't defined anywhere yet (ARCHITECTURE.md calls
# it "a sketch... to be refined by Contributors"), so there is nothing
# honest to point this at until an operator has actually registered
# somewhere. BETAT_AUTO_ANNOUNCE gates an optional, best-effort ping after
# every accepted submission (workflow/api/views.py) — off by default; a
# slow/unreachable registry must never block or fail an accept.
BETAT_REGISTRY_URL = os.environ.get('BETAT_REGISTRY_URL', '')
BETAT_AUTO_ANNOUNCE = os.environ.get('BETAT_AUTO_ANNOUNCE', 'false').lower() in ('1', 'true', 'yes')
