"""
Django settings for betat_community project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = os.environ.get('BETAT_DEBUG', 'true').lower() in ('1', 'true', 'yes')

SECRET_KEY = os.environ.get('BETAT_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Dev-only fallback — never used when DEBUG is False, so it can be
        # committed safely. Production installs must set BETAT_SECRET_KEY.
        SECRET_KEY = 'django-insecure-3bx3ny^00-=-0lpac%@chtl_1u%w8fv(y=0w7$ap8vc&2nc_&2'
    else:
        raise ImproperlyConfigured(
            'BETAT_SECRET_KEY must be set in the environment when BETAT_DEBUG is false.'
        )

# [DEV] Unset — Django's own dev-server host checks stay permissive at DEBUG=True.
# [PROD] Set BETAT_ALLOWED_HOSTS to a comma-separated list of hosts this
# community serves (e.g. archive.yourcommunity.org) — required once DEBUG=False.
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('BETAT_ALLOWED_HOSTS', '').split(',') if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # third-party
    'rest_framework',
    'rest_framework.authtoken',
    # betat apps
    'betat_community.core',
    'betat_community.store',
    'betat_community.communityauth',
    'betat_community.workflow',
    'betat_community.federation',
    'betat_community.bundledui',
] 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Phase 1/2 gate (TODO 07 amendment) — redirects community-facing pages
    # to the installer screen until a CommunityConfig exists. Last in the
    # list: it only needs request.path and the database, nothing earlier
    # middleware provides.
    'betat_community.bundledui.middleware.BetatConfiguredMiddleware',
]

ROOT_URLCONF = 'betat_community.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'betat_community.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Ships permanently — not stripped before packaging (DISTRIBUTION.md "What
# ships", corrected in BLUEPRINT §12 Decision Log). BETAT_DB unset means
# SQLite, zero configuration. Set to a full PostgreSQL URL
# (postgres://user:pass@host:5432/db) and this same installed package
# connects to PostgreSQL — no code changes, no separate settings module.
# This is also how the dual-DB ship gate (BLUEPRINT §0) is run before a
# release: point BETAT_DB at a live Postgres and re-run `pytest tests/`.
# dj_database_url is therefore a plain pyproject.toml dependency, not an
# extra — this import must always succeed, even for SQLite-only installs.
#
# BETAT_DB_SCHEMA (optional, PostgreSQL only): isolates Betat's tables in
# their own schema instead of the default 'public' schema — useful when
# sharing a PostgreSQL server with other applications. Create the schema
# first (`CREATE SCHEMA <name>;`), then set BETAT_DB_SCHEMA=<name>. NOTE:
# framework-production.md's REVOKE/GRANT role setup is written against
# 'public' only — an operator using BETAT_DB_SCHEMA must adapt those
# statements to their schema until that doc is updated (BLUEPRINT §12
# Decision Log, 2026-08-30).
_betat_db = os.environ.get('BETAT_DB')
if _betat_db:
    _db_config = dj_database_url.parse(_betat_db, conn_max_age=600, conn_health_checks=True)
    _betat_db_schema = os.environ.get('BETAT_DB_SCHEMA', '').strip()
    if _betat_db_schema:
        _db_config.setdefault('OPTIONS', {})
        _db_config['OPTIONS']['options'] = f'-c search_path={_betat_db_schema}'
    DATABASES = {'default': _db_config}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(BASE_DIR / 'betat.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
# Reading endpoints are always public (BLUEPRINT §0); writing endpoints
# require a Provenancier/verifier token — issued via rest_framework.authtoken
# at successful communityauth enrollment (§03). "No custom crypto" for token
# issuance (todos/03-authentication.md) — this is DRF's standard mechanism.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

# Discoverability (§09) — see core/announce.py. No default: the registry's
# own announce contract isn't defined anywhere yet (ARCHITECTURE.md calls
# it "a sketch... to be refined by Contributors"), so there is nothing
# honest to point this at until an operator has actually registered
# somewhere. BETAT_AUTO_ANNOUNCE gates an optional, best-effort ping after
# every accepted submission (workflow/api/views.py) — off by default; a
# slow/unreachable registry must never block or fail an accept.
BETAT_REGISTRY_URL = os.environ.get('BETAT_REGISTRY_URL', '')
BETAT_AUTO_ANNOUNCE = os.environ.get('BETAT_AUTO_ANNOUNCE', 'false').lower() in ('1', 'true', 'yes')
