# Generated by Django 5.2.17 on 2026-08-22 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvenanceRecord',
            fields=[
                ('record_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('betat_version', models.CharField(max_length=16)),
                ('timestamp', models.CharField(max_length=32)),
                ('hi_tag', models.BooleanField()),
                ('provenancier', models.JSONField()),
                ('content', models.JSONField()),
                ('community', models.JSONField()),
                ('verification', models.JSONField()),
                ('declaration', models.JSONField()),
                ('record_signature', models.CharField(blank=True, default='', max_length=2048)),
                ('correction_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='store.provenancerecord')),
                ('disputes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputed_by', to='store.provenancerecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
