# Generated by Django 5.2.17 on 2026-08-23 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provenancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=500, unique=True)),
                ('identity_type', models.CharField(choices=[('cryptographic_key', 'Cryptographic key'), ('institutional_id', 'Institutional ID'), ('government_id', 'Government ID'), ('peer_attested', 'Peer attested'), ('pseudonymous_peer_attested', 'Pseudonymous, peer attested')], max_length=32)),
                ('authentication_method', models.CharField(choices=[('cryptographic_signature', 'Cryptographic signature'), ('institutional_endorsement', 'Institutional endorsement'), ('government_id_verification', 'Government ID verification'), ('community_peer_vouching', 'Community peer vouching'), ('behavioral_attestation', 'Behavioral attestation')], max_length=32)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('verification_material', models.JSONField(blank=True, default=dict)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provenancier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
