# Generated by Django 5.2.17 on 2026-09-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerVouchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=500, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('vouchers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
