# Generated by Django 5.2.17 on 2026-09-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityauth', '0002_peervouchrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='peervouchrequest',
            name='founding',
            field=models.BooleanField(default=False, help_text='True for the first two members — admin approval sufficient, no peer vouches required.'),
        ),
    ]
