# Generated by Django 5.2.17 on 2026-09-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityauth', '0003_peervouchrequest_founding'),
    ]

    operations = [
        migrations.AddField(
            model_name='peervouchrequest',
            name='claim_passphrase_hash',
            field=models.CharField(blank=True, default='', help_text="Optional (TODO 13 task 3): lets the applicant retrieve their pending status or, once promoted, their token from a different session/device later, via POST /betat/enroll/claim. Hashed with Django's password hasher (make_password) — never the plaintext passphrase. Blank means the applicant did not set one and has no self-service claim path (same-session polling / admin fallback only).", max_length=200),
        ),
    ]
