# Generated by Django 5.2.17 on 2026-09-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityauth', '0004_peervouchrequest_claim_passphrase_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='peervouchrequest',
            name='requested_vouchers',
            field=models.JSONField(blank=True, default=list, help_text='TODO 14: identity strings of existing members the applicant asked to vouch, set once at enroll time and filtered to real enrolled identities. Purely a per-member "you were asked" flag surfaced by GET /betat/vouch-requests/open — not a vouch itself (that still comes from POST /betat/vouch/{id}).'),
        ),
    ]
