# Generated by Django 5.2.17 on 2026-08-23 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communityauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('location', models.CharField(max_length=1000)),
                ('content_hash', models.CharField(max_length=128)),
                ('language', models.CharField(default='en', max_length=8)),
                ('declaration_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending_review', max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=200)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=1000)),
                ('record_id', models.CharField(blank=True, default='', max_length=64)),
                ('provenancier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='communityauth.provenancier')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
